#!/usr/bin/env dart
// @license
// Copyright (c) 2026 ggsuite
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

import 'dart:io';

import 'package:gg_console_colors/gg_console_colors.dart';

// .............................................................................
const dartEntry = 'lib/src/main.dart';
const generatedFolder = 'typescript/generated';
const wasmName = 'bridge-wasm';

bool debug = false;
bool clean = false;

// .............................................................................
Future<void> main(List<String> args) async {
  debug = args.contains('--debug') || args.contains('-d');
  clean = args.contains('--clean');

  if (clean) {
    await _clean();
  }

  _ensurePrerequisites();
  _ensureGeneratedFolder();

  await _compileToWasm();
  await _wrapWasmIntoTypescript();

  print(green('Build complete.'));
}

// .............................................................................
String get _wasmBase => '$generatedFolder/$wasmName';

// .............................................................................
void _ensurePrerequisites() {
  if (!File(dartEntry).existsSync()) {
    stderr.writeln(red('Missing Dart entry point: $dartEntry'));
    exit(2);
  }
}

void _ensureGeneratedFolder() {
  final dir = Directory(generatedFolder);
  if (!dir.existsSync()) {
    dir.createSync(recursive: true);
  }
}

Future<void> _clean() async {
  final dir = Directory(generatedFolder);
  if (dir.existsSync()) {
    print(darkGray('Cleaning $generatedFolder ...'));
    await dir.delete(recursive: true);
  }
}

// .............................................................................
Future<void> _compileToWasm() async {
  final out = '$_wasmBase.wasm';
  await _run('Compiling $dartEntry → $out', [
    'dart',
    'compile',
    'wasm',
    dartEntry,
    '-o',
    out,
    debug ? '-O0' : '-O4',
    debug ? '--source-maps' : '--no-source-maps',
  ]);
}

Future<void> _wrapWasmIntoTypescript() async {
  final mjsFile = '$_wasmBase.mjs';
  final tsFile = '$_wasmBase.ts';

  print(darkGray('Wrapping $mjsFile → $tsFile'));

  final body = await File(mjsFile).readAsString();
  final wrapped = <String>[
    '// Generated by build.dart. Do not edit.',
    '// @ts-nocheck',
    '/* eslint-disable */',
    '',
    body,
    '',
  ].join('\n');

  await File(tsFile).writeAsString(wrapped);
  await File(mjsFile).delete();
}

// .............................................................................
Future<void> _run(String description, List<String> command) async {
  print(yellow(description));
  final p = await Process.start(
    command.first,
    command.sublist(1),
    mode: ProcessStartMode.inheritStdio,
  );
  final code = await p.exitCode;
  if (code != 0) {
    stderr.writeln(red('Command failed (exit $code): ${command.join(' ')}'));
    exit(code);
  }
}
